# netlify.toml - Netlify Configuration
[build]
  command = "echo 'No build needed'"
  publish = "."

[functions]
  directory = "functions"

# Disable secrets scanning for supabase-config.js
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "supabase-config.js"
  NODE_VERSION = "18"
